export const GLOBAL_CHARACTERS_RELEASE_ORDER = [
  "Special Week",
  "Silence Suzuka",
  "Tokai Teio",
  "Maruzensky",
  "Fuji Kiseki",
  "Oguri Cap",
  "Gold Ship",
  "Vodka",
  "Daiwa Scarlet",
  "Taiki Shuttle",
  "Grass Wonder",
  "Hishi Amazon",
  "Mejiro McQueen",
  "El Condor Pasa",
  "T.M. Opera O",
  "Symboli Rudolf",
  "Air Groove",
  "Agnes Digital",
  "Tamamo Cross",
  "Seiun Sky",
  "Fine Motion",
  "Biwa Hayahide",
  "Mayano Top Gun",
  "Manhattan Cafe",
  "Mihono Bourbon",
  "Mejiro Ryan",
  "Hishi Akebono",
  "Yukino Bijin",
  "Rice Shower",
  "Ines Fujin",
  "Agnes Tachyon",
  "Admire Vega",
  "Inari One",
  "Winning Ticket",
  "Air Shakur",
  "Eishin Flash",
  "Curren Chan",
  "Kawakami Princess",
  "Gold City",
  "Sakura Bakushin O",
  "Shinko Windy",
  "Sweep Tosho",
  "Super Creek",
  "Smart Falcon",
  "Zenno Rob Roy",
  "Tosen Jordan",
  "Nakayama Festa",
  "Narita Brian",
  "Mejiro Palmer",
  "Daiichi Ruby",
  "Mejiro Dober",
  "Nice Nature",
  "King Halo",
  "Matikanetannhauser",
  "Ikuno Dictus",
  "Daitaku Helios",
  "Twin Turbo",
  "Satono Diamond",
  "Kitasan Black",
  "Sakura Chiyono O",
  "Sirius Symboli",
  "Mejiro Ardan",
  "Yaeno Muteki",
  "Tsurumaru Tsuyoshi",
  "Mejiro Bright",
  "Narita Top Road",
  "Symboli Kris S",
  "Copano Rickey",
  "Hokko Tarumae",
  "Wonder Acute",
  "Haru Urara"
];
